# Generated by Django 4.2 on 2023-04-09 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('type', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('color', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='car_images')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_sold', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
