# Generated by Django 4.2 on 2023-05-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0003_car_fuel_type_car_mileage_alter_car_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(max_length=2551),
        ),
    ]
